# Generated by Django 4.1.7 on 2023-04-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=45, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('imc', models.FloatField()),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Fisioterapeuta',
        ),
    ]
