# Generated by Django 4.1.5 on 2023-03-03 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=45, unique=True)),
                ('senha', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('sobrenome', models.CharField(max_length=45)),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('imc', models.FloatField()),
                ('matricula', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fisioterapeuta',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='fisioterapeuta',
            name='matricula',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=45)),
                ('id_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.administrador')),
                ('id_fisioterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.fisioterapeuta')),
            ],
        ),
    ]
