# Generated by Django 4.1.7 on 2023-03-04 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_administrador_paciente_alter_fisioterapeuta_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='id_administrador',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='id_fisioterapeuta',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Fisioterapeuta',
        ),
        migrations.DeleteModel(
            name='Instituicao',
        ),
    ]
