# Generated by Django 4.1.7 on 2023-03-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_remove_instituicao_id_administrador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='sobrenome',
        ),
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
