# Generated by Django 4.1.7 on 2023-03-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_remove_paciente_sobrenome_paciente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
