# Generated by Django 4.1.7 on 2023-03-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_alter_paciente_cpf_alter_paciente_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
