# Generated by Django 4.1.7 on 2023-03-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisioterapeuta', '0002_fisioterapeuta_instituicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fisioterapeuta',
            name='sobrenome',
        ),
    ]
