# Generated by Django 4.1.7 on 2023-03-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisioterapeuta', '0004_alter_fisioterapeuta_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapeuta',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
