# Generated by Django 4.1.7 on 2023-03-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=45, unique=True)),
                ('senha', models.CharField(max_length=45)),
            ],
        ),
    ]
