# Generated by Django 4.1.7 on 2023-03-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_administrador_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='senha',
            field=models.CharField(max_length=128),
        ),
    ]
