# Generated by Django 4.1.7 on 2023-04-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circunstancia', '0001_initial'),
        ('formAFM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formafm',
            name='AFM06',
        ),
        migrations.AddField(
            model_name='formafm',
            name='AFM06',
            field=models.ManyToManyField(null=True, related_name='+', to='circunstancia.circunstancia'),
        ),
    ]
