# Generated by Django 4.1.7 on 2023-04-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formAFM', '0002_remove_formafm_afm06_formafm_afm06'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formafm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
