# Generated by Django 4.1.7 on 2023-03-11 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('fisioterapeuta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField()),
                ('data_retorno', models.DateField(null=True)),
                ('fisioterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisioterapeuta.fisioterapeuta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
