# Generated by Django 4.1.7 on 2023-03-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateField(auto_now_add=True),
        ),
    ]
