# Generated by Django 4.1.7 on 2023-04-10 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisioterapeuta', '0005_alter_fisioterapeuta_nome'),
        ('paciente', '0004_alter_paciente_id'),
        ('consulta', '0003_alter_consulta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fisioterapeuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fisioterapeuta', to='fisioterapeuta.fisioterapeuta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='paciente.paciente'),
        ),
    ]
