# Generated by Django 4.1.7 on 2023-03-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0003_alter_instituicao_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='senha',
            field=models.CharField(max_length=45),
        ),
    ]
