# Generated by Django 4.1.7 on 2023-04-08 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formAFM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circunstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circunstancia', models.CharField(max_length=20)),
                ('formAFM', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='AFM06', to='formAFM.formafm')),
            ],
        ),
    ]
